#!/bin/bash
# This script takes three parameters
#   - A directory
#   - A source extension
#   - A target extension
# and locates every file in that directory that ends in .sourceExtension
# and renames it to be .targetExtension

if [ $# -ne 3 ]; then
  echo "Usage: ${0} dirName sourceExtension targetExtension"
  exit 1
fi

# Keep in mind $1 was given by the user, and may contain spaces.
# if it does, then without the quotes where they are we would have
# problems, because expanding $1 into a string in place with spaces would
# make our loop iterate over two separate files.
for file in "$1"/*.${2}; do
  # Similarly, if the filename contains spaces we must handle that here as well.
  mv "${file}" "${file%.$2}.$3"
done
